# Generated by Django 6.0.5 on 2026-06-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certi', models.CharField(max_length=200)),
                ('dis', models.CharField(max_length=200)),
            ],
        ),
    ]
